### ISSUE TITLE
Vibration sensor implementation missing "touched" state

### ISSUE THREAD

**Issue by timdonovanuk** [Danielhiversen/PyXiaomiGateway#148]
Current implementation supports vibration, tilt, coord & bed (https://github.com/Danielhiversen/PyXiaomiGateway/pull/89#issuecomment-418480291) but there is another state called touched, that shows up in the Aqara app, that is not implemented. Not sure how to run PyXiaomiGateway manually otherwise I'd see what the gateway outputs. Cheers.

**Comment by syssi** [comment]
The event is already supported and called "vibrate". It's just called "touched" at the MiHome app. You should listen for this event:

```
Event: xiaomi_aqara.movement
Parameters:
  entity_id: binary_sensor.vibration_158d0002a4f9f8
  movement_type: vibrate
```
