### ISSUE TITLE
Support for water sensor

### ISSUE THREAD

**Issue by FlorentSueur** [Danielhiversen/PyXiaomiGateway#3]
I can see my water sensor model lumi.sensor_wleak.aq1 in MiHome dev mode. Will home Assistant support it ?

**Comment by syssi** [comment]
I will implement the sensor if you provide some events. Please enable the debug log
```
logger:
 default: warn
  logs:
    homeassistant.components.xiaomi: debug
    homeassistant.components.binary_sensor.xiaomi: debug
    homeassistant.components.sensor.xiaomi: debug
    homeassistant.components.light.xiaomi: debug
    homeassistant.components.switch.xiaomi: debug
```
and provide some lines of different measurements.
